// All the rooms are here. 
// by T. Fujita
// 
// A: Again
// B: Block(Movable)
// E: Enemy
// F: Floor
// G: Goal
// P: Player
// W: Wall

var room = [];
    room[0] = [ "WwwwwGwW",
		"WFFEFFFW",
		"WFFFFFFW",
		"WFPFFFFW",
		"WFFFFFFW",
		"WwwwwwwA"]

    room[1] = [ "WwwwwGwW",
		"WFFEFBFW",
		"WFFFFFFW",
		"WFPFFEFW",
		"WFFFFFFW",
		"WwwwwwwA"]

    room[2] = [ "WwwwwwwwwwwwwGwW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFEFFW",
		"WFFFFEFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFEFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFPFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwA"]

    room[3] = [ "WwwwwwwwwwwwwGwW",
		"WFFFFFFFFFFFEFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFPFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwA"]

    room[4] = [ "WwwwwwwGwwwwwwwW",
		"WFFFFFFFFFEFFFFW",
		"WFFFFEFFFFFFFFFW",
		"WFFFFFFFEFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFPFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwA"]

    room[5] = [ "WwwwwwwGwwwwwwwW",
		"WFFFFBFEFBFFFFFW",
		"WFFFFBFFFBFFFFFW",
		"WFFFFBFFEBFFFFFW",
		"WFFFFBEFFBFFFFFW",
		"WFFFFBBBBBFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFPFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwA"]

    room[6] = [ "WwwwwwwwGwwwwwwW",
		"WFFFFFFEFFFFFFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFFFFEFFFFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFEFFFFFFFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFFFFEFFFFFW",
		"WBBBBBBBBBBBBBBW",
		"WFFFFFFFFFFFFFFW",
		"WFFPFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwA"]

    room[7] = [ "WwwwwwwGwwwwwwwW",
		"WBFBFBFBFBFBFBFW",
		"WFBFBFBFBFBFBFBW",
		"WBFBFBFBFBFBFBFW",
		"WFBFBFBFBFBFBFBW",
		"WBFBFBFBFBFBFBFW",
		"WFBFBFBFBFBFBFBW",
		"WBFBFBFBFBFBFBFW",
		"WFBFBFBFBFBFBFBW",
		"WBFBFBFBFBFBFBFW",
		"WFPFFFFFFFFFEFFW",
		"WwwwwwwwwwwwwwwA"]

    room[8] = [ "WwwwwwwwwwwwwGwW",
		"WFFBFFFFEFFFFBFW",
		"WFFFBFBFBFBFBFFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFPBFFFFFFBFFFFW",
		"WwwwwwwwwwwwwwwA"]

    room[9] = [ "WwwwwwwwwwwwwGwW",
		"WFFBFBFBFBFBFBFW",
		"WFFFBFBFBFBFBFFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWEWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFFWFWFWFWFWFWFW",
		"WFPBFFFFFFBFFFFW",
		"WwwwwwwwwwwwwwwA"]

    room[10] = ["WwwwwwwGwwwwwwwW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WBWwwBWFFWBWwFBW",
		"WFWFFFWwFWFWFWFW",
		"WFWwEFWwwWFWFWFW",
		"WFWFFFWFwWFWFWFW",
		"WBWwwBWFFWBWwFBW",
		"WFFFFFFFFFFFFFFW",
		"WFFFFFFFFFFFFFFW",
		"WFPFFFFFFFFFFFFW",
		"WwwwwwwwwwwwwwwA"]

